server:
  port: 8771
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          search-paths: ocloud-repo
          uri: https://github.com/jing2017feng/ocloud.git
          username: jing2008feng@163.com
          password: ming2015feng
          default-label: master
logging:
  file: /log/ocloud-config.log
  level:
    root: INFO   