server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
zuul:
  sensitive-headers: Cookie,Set-Cookie,Authorization
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: ocloud-service
#    app:
#      path: /app/**
#      serviceId: ocloud-app
#    api-url:
#      path: /api/**
#      url: forward:/home