spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://jingfeng:minghui@localhost:8761/eureka/
  instance:
    appname: ocloud-service