server:
  port: 8050
spring:
  application:
    name: ocloud-monitor
endpoints:
  health:
    sensitive: false
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/ 
  #设置权限，故需要通过账号密码获取注册信息 
  instance: 
    metadata-map: 
      user.name: jingfeng 
      user.password: minghui 