server:
  port: 7050
spring:
  mvc:
    async:
      request-timeout: 15000
  thymeleaf:
    cache: false
  redis:
    #cluster:
      #nodes:
        #- 47.94.174.38:7000
        #- 47.94.174.38:7001
        #- 47.94.174.38:7002
        #- 47.94.174.38:7003
        #- 47.94.174.38:7004
        #- 47.94.174.38:7005
      #max-redirects: 3
      host: localhost
      port: 6379
      database: 0
      timeout: 3000
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: 2000
  session:
    store-type: redis
  sleuth:
    sampler:
      percentage: 1.0
endpoints:
  restart:
    enabled: true
eureka:
  instance:
    prefer-ip-address: true
info: 
  app: 
    name: ${spring.application.name}
    version: v1