server:
  port: 7050
spring:
  mvc:
    async:
      request-timeout: 15000
  thymeleaf:
    cache: false
eureka:
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true