server:
  port: 7050
spring:
  mvc:
    async:
      request-timeout: 15000
  thymeleaf:
    cache: false
eureka:
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
    
#ribbon负载均衡策略
ocloud-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule