spring:
  application:
    name: ocloud-discovery
  cloud:
    config:
      enabled: true
      uri: http://my.ocloudwork.com:8771/
  security:
    user:
      name: jingfeng
      password: minghui